baseURL = 'https://claydav.is/'
languageCode = 'en-us'
title = 'Clay Davis'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[imaging]
  quality = 80
  resampleFilter = "Lanczos"
  anchor = "Center"
  bgColor = "#ffffff"

[params]
  author = "Clay Davis"
  description = "PhD candidate in sociology and Mellon Cluster Fellow in science studies at Northwestern University"
  
[params.colors]
  primary = "#2D6F59"
  primary_medium = "#6c9a8a"
  primary_light = "#abc5bc"
  surface = "#ffffff"
  gray = "#f3f3f3"
  text = "#000000"
  text_secondary = "#333333"

[params.images]
  # Homepage publication cards (landscape)
  home_width = 480
  home_height = 200
  
  # List item thumbnails (used across site, including home cards)
  list_width = 120
  list_height = 155
  
  # Article headers
  header_width = 500
  header_height = 300
  
  # Profile images (multiple responsive sizes)
  profile_small = 200
  profile_medium = 300
  profile_large = 400

[menu]
  [[menu.main]]
    name = "About"
    url = "/"
    pageRef = "/"
    weight = 10
  
  [[menu.main]]
    name = "Research"
    url = "/publications/"
    pageRef = "/publications"
    weight = 10
  
  [[menu.main]]
    name = "CV"
    url = "/cv/"
    pageRef = "/cv"
    weight = 20
    
  [[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    pageRef = "/teaching"
    weight = 30
    
  [[menu.main]]
    name = "Meet with me"
    url = "/meetwithme/officehours/"
    pageRef = "/meetwithme/officehours"
    weight = 40
