baseURL = 'https://claydav.is/'
languageCode = 'en-us'
title = 'Clay Davis'

[imaging]
  quality = 75

[params]
  author = "Clay Davis"
  description = "PhD candidate in sociology and Mellon Cluster Fellow in science studies at Northwestern University"
  
[params.colors]
  primary = "#2D6F59"
  primary_medium = "#6c9a8a"
  primary_light = "#abc5bc"
  surface = "#ffffff"
  gray = "#f3f3f3"
  text = "#000000"
  text_secondary = "#333333"

[pagination]
  disableAliases = false
  pagerSize = 10
  path = "page"


[menu]
  [[menu.main]]
    name = "About"
    url = "/"
    pageRef = "/"
    weight = 10
  
  [[menu.main]]
    name = "Research"
    url = "/research/"
    pageRef = "/research"
    weight = 10
  
  [[menu.main]]
    name = "CV"
    url = "/cv/"
    pageRef = "/cv"
    weight = 20
    
  [[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    pageRef = "/teaching"
    weight = 30
    
  [[menu.main]]
    name = "Meet with me"
    url = "/meetwithme/officehours/"
    pageRef = "/meetwithme/officehours"
    weight = 40
